import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/layout/Layout'
import utilStyles from '../styles/utils.module.css'

const Home: NextPage = () => {
  return (
    <Layout home>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <section className={utilStyles.headingMd}>
        <p>
          Hello, I'm Andres Alcocer and I want to become a software developer
        </p>
        <p>
          (This is a sample website - you’ll be building a site like this on{' '}
          <a href='https://nextjs.org/learn'>our Next.js tutorial</a>.)
        </p>
      </section>

      <footer></footer>
    </Layout>
  )
}

export default Home
