import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import Layout from '../components/layout/Layout'
import utilStyles from '../styles/utils.module.scss'
import { getSortedPostsData } from '../lib/api'
import Date from '../components/Date'
import ProfileImg from '../public/profile-img.png'

interface IAllPostData {
  allPostsData: Array<{ slug: string; date: string; title: string }>
}

export async function getStaticProps() {
  const allPostsData = getSortedPostsData()
  return {
    props: {
      allPostsData,
    },
  }
}

const Home = ({ allPostsData }: IAllPostData) => {
  return (
    <Layout home>
      <Head>
        <title>Andres Alcocer | Blog</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className={utilStyles.homeContainer}>
        <section style={{ width: '70%' }}>
          <ul className={utilStyles.list}>
            {allPostsData.map(({ slug, date, title }) => (
              <li className={utilStyles.listItem} key={slug}>
                <Link href={`/posts/${slug}`}>
                  <a>{title}</a>
                </Link>
                <br />
                <small className={utilStyles.lightText}>
                  <Date dateString={date} />
                </small>
              </li>
            ))}
          </ul>
        </section>
        <section style={{ width: '30%', textAlign: 'center' }}>
          <div style={{ padding: '30px', paddingTop: '0' }}>
            <Image
              className={utilStyles.profileImg}
              src={ProfileImg}
              alt='head shot'
            />
          </div>
          <p style={{ marginTop: '0' }}>
            Hi, I am Andres Alcocer and I like everything involving the world of
            frontend development. When I am not coding or writing for my blog I
            like to try new grilling recipes and keep up with the latest
            football stats.
          </p>
          <p>You can find me at:</p>
        </section>
      </div>
    </Layout>
  )
}

export default Home
